# Generated by Django 2.2.1 on 2019-05-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='关键词')),
                ('source', models.IntegerField(default=0, verbose_name='关键词来源')),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类')),
                ('order', models.IntegerField(help_text='从上一个分类往后排', verbose_name='分类顺序')),
                ('description', models.TextField(default='用于SEO', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类')),
                ('description', models.TextField(default='用于SEO', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网址名称')),
                ('url', models.CharField(max_length=128, verbose_name='网址')),
                ('icon', models.CharField(default='/static/logo@1x.png', max_length=128, verbose_name='logo')),
                ('keywords', models.ManyToManyField(help_text='文章关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够', to='link.Keyword', verbose_name='文章关键词')),
                ('sort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='link.Sort', verbose_name='网址分类')),
                ('tags', models.ManyToManyField(to='link.Tags', verbose_name='网址标签')),
            ],
        ),
    ]
